name: Run Cucumber Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Install Chrome and ChromeDriver
        run: |
          # Install required system dependencies
          sudo apt-get update
          
          # Install Chrome from official Google repo (modern method)
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /etc/apt/keyrings/google-chrome.gpg
          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Kill existing Chrome processes
        run: pkill -f chrome || true

      - name: Run Cucumber Tests
        run: export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 +extension RANDR > /dev/null 2>&1 &
          mvn test \
          -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver \
          -DchromeOptions.args="--no-sandbox,--disable-dev-shm-usage,--headless=new,--remote-debugging-port=9222,--window-size=1920x1080,--disable-gpu,--disable-software-rasterizer"
      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v4.0.0
        with:
          name: Cucumber-Reports
          path: target/cucumber-html-reports/

      - name: Set up environment variables for EVRI credentials
        run: |
          echo "EVRIEMAIL=${{ secrets.EVRIEMAIL }}" >> $GITHUB_ENV
          echo "EVRIPASSWORD=${{ secrets.EVRIPASSWORD }}" >> $GITHUB_ENV

      - name: Use EVRI credentials in your build
        run: |
          echo "Using EVRI credentials"
          echo "Email: $EVRIEMAIL"
          echo "Password: $EVRIPASSWORD"

      
