name: Run Cucumber Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v4.0.0
        with:
          name: Cucumber-Reports
          path: target/cucumber-html-reports/

      - name: Build with Maven
        run: mvn clean install  # Replace with your build command

      - name: Run Cucumber Tests
        run: mvn test  # Replace with your test command

      
