name: Run Cucumber Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Install Chrome and ChromeDriver
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y wget curl unzip xvfb libxi6 libgbm-dev

          # Install Chrome (stable channel)
          sudo mkdir -p /usr/share/apt/keyrings
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/apt/keyrings/google-chrome.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

          # Install matching ChromeDriver
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          CHROMEDRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Kill existing Chrome processes
        run: pkill -f chrome || true

      - name: Run Cucumber Tests
        run: mvn test -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver -Dheadless=true -Dbrowser=chrome -DchromeOptions.args="--no-sandbox,--disable-dev-shm-usage,--headless,--remote-debugging-port=9222"

      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v4.0.0
        with:
          name: Cucumber-Reports
          path: target/cucumber-html-reports/

      - name: Set up environment variables for EVRI credentials
        run: |
          echo "EVRIEMAIL=${{ secrets.EVRIEMAIL }}" >> $GITHUB_ENV
          echo "EVRIPASSWORD=${{ secrets.EVRIPASSWORD }}" >> $GITHUB_ENV

      - name: Use EVRI credentials in your build
        run: |
          echo "Using EVRI credentials"
          echo "Email: $EVRIEMAIL"
          echo "Password: $EVRIPASSWORD"

      
