name: Run Cucumber Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Install Chrome and ChromeDriver
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y wget curl unzip

          # Install Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt --fix-broken install -y

          # Install ChromeDriver
          LATEST_CHROMEDRIVER=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

          # Verify installations
          google-chrome-stable --version
          chromedriver --version

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Cucumber Tests
        run: mvn test -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver -Dheadless=true

      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v4.0.0
        with:
          name: Cucumber-Reports
          path: target/cucumber-html-reports/

      - name: Set up environment variables for EVRI credentials
        run: |
          echo "EVRIEMAIL=${{ secrets.EVRIEMAIL }}" >> $GITHUB_ENV
          echo "EVRIPASSWORD=${{ secrets.EVRIPASSWORD }}" >> $GITHUB_ENV

      - name: Use EVRI credentials in your build
        run: |
          echo "Using EVRI credentials"
          echo "Email: $EVRIEMAIL"
          echo "Password: $EVRIPASSWORD"

      - name: Kill existing Chrome processes
        run: pkill -f chrome || true
