name: Run Cucumber Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Generate Reports
        run: mvn clean verify

      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v4
        with:
          name: Cucumber-Reports
          path: target/cucumber-html-reports/