name: Run Cucumber Tests

on:
  push:
    branches:
      - master  # Adjust to your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Adjust to your project's Java version
          distribution: 'adopt'  # Specify 'adopt' for AdoptOpenJDK

      - name: Build with Maven
        run: mvn clean install  # Replace with your build command

      - name: Run Cucumber Tests
        run: mvn test  # Replace with your test command